### PR TITLE
fix: Save changes from null

### PR DESCRIPTION
**Pull request by OscarLlamas6**

### CODE REVIEW

**Comment by WelingtonMonteiro** [comment]
Could you add tests to validate this scenario?

**Comment by WelingtonMonteiro** [comment]
I need a scenario in which this case is occurring for testing! Could you send me an example?

**Comment by OscarLlamas6** [comment]
> I need a scenario in which this case is occurring for testing! Could you send me an example?

I have a schema where a numeric attribute must have a "null" value by default (any numeric value affects business logic since it is a value that is used as a ratio constant to calculate an equation) users can later assign a numeric value to it. Here an example:

- from "null" -> to "0.5" (this is not saving a change log)
- from "0.5" -> "0.6" (this does generate a change log)

In this case I am looking to be able to save both logs in the history trace collection.

**Comment by WelingtonMonteiro** [comment]
New pull request created and new version with fix implemented.
Thank you! In the future new features and bugs fixed!
Issue #9 
[Pull request ](https://github.com/WelingtonMonteiro/mongoose-history-trace/commit/6d2f9c112ebd3cdf6033b7e68809f50cf5e398a4)

**Pull request closed without merging**
